-- =============================================================================
-- Ternium Front – PostgreSQL Database Schema
-- =============================================================================
-- Source: src/types/database.ts (auto-generated by `supabase gen types typescript`)
-- Database engine: PostgreSQL (hosted on Supabase, project nsxilbneojeaaelplcxm)
--
-- Tables
--   clients, roles, users, client_workers,
--   dispatch_validation, execution_details,
--   leaderboard_snapshots, product, specs,
--   shipping_info, programing_instructions, orders,
--   order_offers_specs, order_offers, user_activity_log
--
-- Enums
--   dispatch_enum_status, execution_details_enum,
--   order-status-enum, programing-status-enum, shipping_info_status
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions (Supabase enables these by default)
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------

CREATE TYPE dispatch_enum_status AS ENUM (
  'Aceptado',
  'Pendiente',
  'Rechazado'
);

CREATE TYPE execution_details_enum AS ENUM (
  'Aceptado',
  'Rechazado',
  'Pendiente'
);

-- NOTE: The names "order-status-enum" and "programing-status-enum" (with hyphens
-- and the single-m spelling of "programing") are the exact identifiers used in the
-- Supabase production database, as reflected in the auto-generated
-- src/types/database.ts file. They are preserved here for accuracy and must be
-- quoted wherever they are referenced in SQL.

CREATE TYPE "order-status-enum" AS ENUM (
  'Aceptado',
  'Rechazado',
  'Revision Cliente',
  'Revision Operador'
);

CREATE TYPE "programing-status-enum" AS ENUM (
  'Asignado',
  'Sin asignar',
  'Reasignado'
);

CREATE TYPE shipping_info_status AS ENUM (
  'En ruta',
  'Pendiente',
  'Rechazado',
  'Entregado'
);

-- ---------------------------------------------------------------------------
-- clients
-- ---------------------------------------------------------------------------
CREATE TABLE clients (
  id   uuid        NOT NULL DEFAULT uuid_generate_v4(),
  name text        NOT NULL,

  CONSTRAINT clients_pkey PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- roles
-- ---------------------------------------------------------------------------
CREATE TABLE roles (
  id   serial      NOT NULL,
  name text        NOT NULL,

  CONSTRAINT roles_pkey PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id              uuid          NOT NULL DEFAULT uuid_generate_v4(),
  name            text          NOT NULL,
  second_name     text          NOT NULL,
  email           text          NOT NULL,
  role_id         integer       NOT NULL,
  active          boolean       NOT NULL DEFAULT true,
  created_at      timestamptz   NOT NULL DEFAULT now(),
  offboarded_at   timestamptz,
  offboarded_by   uuid,
  reactivated_at  timestamptz,
  reactivated_by  uuid,

  CONSTRAINT users_pkey PRIMARY KEY (id),

  CONSTRAINT users_role_id_fkey
    FOREIGN KEY (role_id) REFERENCES roles (id),

  CONSTRAINT users_offboarded_by_fkey
    FOREIGN KEY (offboarded_by) REFERENCES users (id),

  CONSTRAINT users_reactivated_by_fkey
    FOREIGN KEY (reactivated_by) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- client_workers  (user ↔ client assignment; each user belongs to at most one client)
-- ---------------------------------------------------------------------------
CREATE TABLE client_workers (
  client_id  uuid  NOT NULL,
  user_id    uuid  NOT NULL,

  CONSTRAINT client_workers_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES clients (id),

  CONSTRAINT client_workers_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- One user can only be assigned to one client at a time.
CREATE UNIQUE INDEX client_workers_user_id_key ON client_workers (user_id);

-- ---------------------------------------------------------------------------
-- dispatch_validation
-- ---------------------------------------------------------------------------
CREATE TABLE dispatch_validation (
  id           serial               NOT NULL,
  approved_at  timestamptz,
  approved_by  uuid,
  status       dispatch_enum_status,
  updated_at   timestamptz,

  CONSTRAINT dispatch_validation_pkey PRIMARY KEY (id),

  CONSTRAINT dispatch_validation_approved_by_fkey
    FOREIGN KEY (approved_by) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- execution_details
-- ---------------------------------------------------------------------------
CREATE TABLE execution_details (
  id                  serial                 NOT NULL,
  note                text,
  recorded_by         uuid,
  shipping_packaging  text,
  status              execution_details_enum NOT NULL DEFAULT 'Pendiente',
  updated_at          timestamptz,
  weight              numeric,

  CONSTRAINT execution_details_pkey PRIMARY KEY (id),

  CONSTRAINT execution_details_recorded_by_fkey
    FOREIGN KEY (recorded_by) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- leaderboard_snapshots
-- ---------------------------------------------------------------------------
CREATE TABLE leaderboard_snapshots (
  id               integer       GENERATED ALWAYS AS IDENTITY,
  actions_count    integer       NOT NULL DEFAULT 0,
  composite_score  numeric,
  created_at       timestamptz   NOT NULL DEFAULT now(),
  metadata         jsonb,
  period_end       timestamptz   NOT NULL,
  period_start     timestamptz   NOT NULL,
  quality_score    numeric,
  rank_in_role     integer,
  role_name        text          NOT NULL,
  user_id          uuid          NOT NULL,

  CONSTRAINT leaderboard_snapshots_pkey PRIMARY KEY (id),

  CONSTRAINT leaderboard_snapshots_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- product
-- ---------------------------------------------------------------------------
CREATE TABLE product (
  id         serial  NOT NULL,
  client_id  uuid    NOT NULL,
  master     text    NOT NULL,
  pt         text    NOT NULL,

  CONSTRAINT product_pkey PRIMARY KEY (id),

  CONSTRAINT product_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES clients (id)
);

-- ---------------------------------------------------------------------------
-- specs  (order specifications)
-- ---------------------------------------------------------------------------
CREATE TABLE specs (
  id                      serial   NOT NULL,
  coil_orientation        text,
  inner_diameter          numeric,
  maximum_pallet_width    numeric,
  maximum_shipping_weight numeric,
  minimum_shipping_weight numeric,
  outer_diameter          numeric,
  pieces_per_package      integer,
  product_id              integer,
  shipping_packaging      text,
  width                   numeric,

  CONSTRAINT specs_pkey PRIMARY KEY (id),

  CONSTRAINT specs_product_id_fkey
    FOREIGN KEY (product_id) REFERENCES product (id)
);

-- ---------------------------------------------------------------------------
-- shipping_info
-- ---------------------------------------------------------------------------
CREATE TABLE shipping_info (
  id                       serial               NOT NULL,
  approved_at              timestamptz,
  plates                   text,
  scheduled_departure_date timestamptz,
  shipped_at               timestamptz,
  status                   shipping_info_status,
  tar                      text,

  CONSTRAINT shipping_info_pkey PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- programing_instructions
-- ---------------------------------------------------------------------------
CREATE TABLE programing_instructions (
  id             serial                    NOT NULL,
  assigned_date  timestamptz,
  note           text,
  responsible    uuid,
  status         "programing-status-enum",
  updated_at     timestamptz,

  CONSTRAINT programing_instructions_pkey PRIMARY KEY (id),

  CONSTRAINT programing_instructions_responsible_fkey
    FOREIGN KEY (responsible) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
CREATE TABLE orders (
  id                         serial               NOT NULL,
  client_id                  uuid                 NOT NULL,
  contra_offer               boolean              NOT NULL DEFAULT false,
  created_at                 timestamptz          NOT NULL DEFAULT now(),
  dispatch_validation_id     integer,
  execution_details_id       integer,
  product_id                 integer              NOT NULL,
  programing_instructions_id integer,
  reviewed                   boolean              NOT NULL DEFAULT false,
  reviewed_by                uuid,
  shipping_info_id           integer,
  specs_id                   integer              NOT NULL,
  status                     "order-status-enum"  NOT NULL DEFAULT 'Revision Operador',
  worker_id                  uuid                 NOT NULL,

  CONSTRAINT orders_pkey PRIMARY KEY (id),

  CONSTRAINT orders_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES clients (id),

  CONSTRAINT orders_dispatch_validation_id_fkey
    FOREIGN KEY (dispatch_validation_id) REFERENCES dispatch_validation (id),

  CONSTRAINT orders_execution_details_id_fkey
    FOREIGN KEY (execution_details_id) REFERENCES execution_details (id),

  CONSTRAINT orders_product_id_fkey
    FOREIGN KEY (product_id) REFERENCES product (id),

  CONSTRAINT orders_programing_instructions_id_fkey
    FOREIGN KEY (programing_instructions_id) REFERENCES programing_instructions (id),

  CONSTRAINT orders_reviewed_by_fkey
    FOREIGN KEY (reviewed_by) REFERENCES users (id),

  CONSTRAINT orders_shipping_info_id_fkey
    FOREIGN KEY (shipping_info_id) REFERENCES shipping_info (id),

  CONSTRAINT orders_specs_id_fkey
    FOREIGN KEY (specs_id) REFERENCES specs (id),

  CONSTRAINT orders_worker_id_fkey
    FOREIGN KEY (worker_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------------
-- order_offers_specs  (specs attached to a counter-offer)
-- Note: inner_diameter and outer_diameter are stored as text here,
--       unlike the numeric columns in the `specs` table.
-- ---------------------------------------------------------------------------
CREATE TABLE order_offers_specs (
  id                      serial   NOT NULL,
  coil_orientation        text,
  inner_diameter          text,
  maximum_pallet_width    numeric,
  maximum_shipping_weight numeric,
  minimum_shipping_weight numeric,
  outer_diameter          text,
  pieces_per_package      integer,
  product_id              integer,
  shipping_packaging      text,
  width                   numeric,

  CONSTRAINT order_offers_specs_pkey PRIMARY KEY (id),

  CONSTRAINT order_offers_specs_product_id_fkey
    FOREIGN KEY (product_id) REFERENCES product (id)
);

-- ---------------------------------------------------------------------------
-- order_offers  (counter-offers made against an order)
-- ---------------------------------------------------------------------------
CREATE TABLE order_offers (
  id            serial       NOT NULL,
  created_at    timestamptz,
  created_by    uuid,
  new_specs_id  integer,
  note          text,
  order_id      integer,

  CONSTRAINT order_offers_pkey PRIMARY KEY (id),

  CONSTRAINT order_offers_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users (id),

  CONSTRAINT order_offers_new_specs_id_fkey
    FOREIGN KEY (new_specs_id) REFERENCES order_offers_specs (id),

  CONSTRAINT order_offers_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES orders (id)
);

-- ---------------------------------------------------------------------------
-- user_activity_log
-- ---------------------------------------------------------------------------
CREATE TABLE user_activity_log (
  id           integer      GENERATED ALWAYS AS IDENTITY,
  action_type  text         NOT NULL,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  entity_id    integer      NOT NULL,
  entity_type  text         NOT NULL,
  metadata     jsonb,
  user_id      uuid         NOT NULL,

  CONSTRAINT user_activity_log_pkey PRIMARY KEY (id),

  CONSTRAINT user_activity_log_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id)
);
